### ISSUE TITLE
Leaking UDP file descriptors 

### ISSUE THREAD

**Issue by jordanebelanger** [apple/swift-statsd-client#14]
I ran into an issue whereas the statsd client seem to be leaking udp file descriptors.
![](https://cdn.discordapp.com/attachments/448584561845338139/684093879519019008/unknown.png)
That's a screenshot of `lsof -i` of my vapor app after a minute or two being up and receiving a couple healthcheck calls. The number of upd fd grows linearly over time. 

These remain open forever and there will be thousands of them after a day. 

My app is running inside a docker container posting statsd events to "0.0.0.0" on port "8125", it may or may not be related to some port configuration issue on the docker container itself, but regardless I think a port issue should not lead to this behaviour.

**Comment by weissi** [comment]
CC @tomerd

**Comment by tomerd** [comment]
thanks for reporting @jordanebelanger will look into this asap

**Comment by tomerd** [comment]
ugh, this is def a regression from https://github.com/apple/swift-statsd-client/pull/9

**Comment by tomerd** [comment]
@jordanebelanger fix in `1.0.0-alpha.3`, lmk if you run into any further issues
